### ISSUE TITLE
Question: do you plan to port Cache Flag to Craft 3?

### ISSUE THREAD

**Issue by tomdavies** [mmikkel/CacheFlag-Craft#10]
Thanks for Cache Flag - it's super useful. Do you currently have any plans to migrate it to Craft3 (in due course, once things settle down etc)? 

Obviously I'm not expecting a promise signed in blood, more of a general indication of likelihood. I'm doing my due diligence before using on a project where I want to keep an upgrade path to 3 open.

Cheers

**Comment by mmikkel** [comment]
Hi @tomdavies - apologies for the late answer. Its more likely than not that I'll port Cache Flag to Craft 3, eventually.
