### ISSUE TITLE
Does CacheFlag provide any hooks/events I can respond to?

### ISSUE THREAD

**Issue by cmalven** [mmikkel/CacheFlag-Craft#13]
I have a situation where it would be very useful to listen for CacheFlag to clear any of its caches and respond. Does CacheFlag currently provide any way to listen for cache clearing events?

**Comment by mmikkel** [comment]
Hi @cmalven, thanks for contributing!

The answer is no, but that's a good feature request. Marking this issue as such. Pull requests are always very welcome!

**Comment by mmikkel** [comment]
Hi @cmalven – I just released [Cache Flag v. 1.1.10](https://github.com/mmikkel/CacheFlag-Craft/releases/tag/v.1.1.10), which raises events just before and immediately after flagged template caches are cleared/deleted – see https://github.com/mmikkel/CacheFlag-Craft#events for more info.
