### ISSUE TITLE
CacheFlags Live Preview Bug

### ISSUE THREAD

**Issue by michaelramuta** [mmikkel/CacheFlag-Craft#15]
I have a project that uses both CacheFlags and regular Craft caching, and on pages with both I am seeing content repeated twice in LivePreview. I've done some digging in CacheFlag_Node.php and haven't been able to get it fixed yet. Will make a PR if I have any luck!

**Comment by mmikkel** [comment]
Hi @michaelramuta – thanks for contributing! I haven't seen or been made aware of any issues w/ Cache Flag and Live Preview before. If you want to post some code or give me access to your project's repo I can give it a look when I have the time – or if you do figure out the issue and a fix, I'll buy you a very big beer for submitting a pull request :)

**Comment by mmikkel** [comment]
Hi @michaelramuta – I noticed that the [Cold Cache](https://github.com/pixelandtonic/ColdCache#111) plugin (which Cache Flag is heavily based on in that it borrows most of it's Twig tag implementation from it) has had what is probably the same bug as the one you describe. P&T pushed a fix for it a few days ago; I'm going to take a look at their fix ASAP - hopefully it's the same issue and the fix will work for CF as well :)

**Comment by Moorst** [comment]
I can confirm this is happening for me too

**Comment by michaelramuta** [comment]
@mmikkel thanks for pointing me in the right direction! Testing on my end looks good.

Next time you're in Chicago I'll trade you a beer for a Chicago dog!

**Comment by mmikkel** [comment]
This should be fixed in [CacheFlag v. 1.1.9](https://github.com/mmikkel/CacheFlag-Craft/releases/tag/1.1.9) – @michaelramuta!
