### ISSUE TITLE
Bug: Does not initialise event listeners on Console requests

### ISSUE THREAD

**Issue by rungta** [mmikkel/CacheFlag-Craft#16]
After peeking inside the plugin’s `init` method I realised that the event listeners that bust the cache are only initialised on Control Panel requests. While it makes sense to avoid the overhead for regular front-end HTTP requests, this also leaves out instances when a command is triggered via the console.

There are many legitimate use cases for triggering element saves via console commands (import scripts, console based task runners, etc). My particular use case that unearthed this bug was attempting to bust caches for scheduled entries using the [Scheduler plugin](https://github.com/supercool/Scheduler). Scheduler essentially uses a cron job to re-save _pending_ elements at their scheduled `postDate`s, and being able to bust caches at this juncture would be super useful.

(P.S. – Thanks a lot for a great plugin!)

**Comment by mmikkel** [comment]
Hi @rungta – thanks a lot for contributing. I completely agree with you, and I think the overhead w/ those four event listeners is a complete non-issue. As such, I've removed the test for the request type completely in [CacheFlag v. 1.1.8](https://github.com/mmikkel/CacheFlag-Craft/releases/tag/1.1.8) – should work for both console commands and non-CP HTTP requests now.

**Comment by rungta** [comment]
Excellent move. Thanks Mikkel!
