### ISSUE TITLE
Easy way to disable cacheflag in devmode

### ISSUE THREAD

**Issue by manomoul** [mmikkel/CacheFlag-Craft#18]
When working on a project, I don't want to remove the cacheflag tags all the time. 
Is there an easy way to make cacheflag not cache in devMode?

**Comment by mmikkel** [comment]
If you set the [`enableTemplateCaching`](https://craftcms.com/docs/config-settings#enableTemplateCaching) config setting to `false`, CacheFlag won't cache anything.

**Comment by bryantAXS** [comment]
Hmm I tired this, not working for me...

**Comment by mmikkel** [comment]
CacheFlag piggybacks on Craft's built-in cache functionality, and doesn't work any differently than the native [`{% cache %}`](https://craftcms.com/docs/templating/cache) tag in this respect. I just tested it to make sure (latest version, [1.1.9](https://github.com/mmikkel/CacheFlag-Craft/releases/tag/1.1.9)), and CacheFlag does *not* create any caches when the `enableTemplateCaching` config setting is set to `false`.

Which version of CacheFlag are you using? Are you absolutely sure you've added `'enableTemplateCaching' => false,` to your `config.php` file (for the correct environment)? If you replace your `{% cacheflag %}` tags with `{% cache %}`, are caches still being added?
