### ISSUE TITLE
PHP notice `Undefined variable: tags` when clearing individual cache

### ISSUE THREAD

**Issue by johndwells** [mmikkel/CacheFlag-Craft#2]
Whenever I click any of the "Clear caches" beside an individual element type setting, I get the following PHP notice:

`Undefined variable: tags`

Looks like line 111 from CacheFlagController.php should instead use the `$flags` variable.

Cheers!

**Comment by mmikkel** [comment]
Thanks for reporting, @johndwells! I'll get that sorted ASAP.
