### ISSUE TITLE
Craft 3 Version of CacheFlag

### ISSUE THREAD

**Issue by ghost** [mmikkel/CacheFlag-Craft#22]
Hi there, was curious if there are plans to port CacheFlag to Craft 3.

**Comment by mmikkel** [comment]
Hi @mjatharvest – thanks for your interest. I'm going to port CacheFlag to Craft 3 (either as-is or as part of a more ambitious caching plugin), but I don't know when it'll happen.

**Comment by mmikkel** [comment]
@mjatharvest Had some free time on my hands, and decided to port Cache Flag to Craft 3 more or less as-is – check out https://github.com/mmikkel/CacheFlag-Craft3.

Not in the Plugin Store yet, going to put it through the ringer first and see if something breaks. Much obliged if you want to help me test it!

**Comment by ghost** [comment]
@mmikkel Thanks. I had started going a different route for my current Craft 3 needs, but I will try testing this out on my next Craft 3 update.
