### ISSUE TITLE
Plugin fails on Craft Client 2.5.2763

### ISSUE THREAD

**Issue by pauliusef** [mmikkel/CacheFlag-Craft#3]
Just by opening the Cache Flag tab the plugin fails. As I know Craft client doesn't support user groups. Is there a possibility that you will include a fix for this situation?

`
Property "Craft\WebApp.userGroups" is not defined.
/home/vagrant/web/osl/craft/app/framework/base/CModule.php(105)
`

**Comment by mmikkel** [comment]
Hello @pauliusef – thanks a lot for reporting! I'll get this patched ASAP.

**Comment by mmikkel** [comment]
Hey @pauliusef – sorry this took a while. Should be fixed now :)
