### ISSUE TITLE
Unknown cacheflag tag in craft.log

### ISSUE THREAD

**Issue by ghost** [mmikkel/CacheFlag-Craft#4]
As I've been experimenting with cacheflag, I've seen lines like this in craft's log file

2016/04/26 03:01:03 [error] [exception.Twig_Error_Syntax] Twig_Error_Syntax: Unknown "cacheflag" tag in "_layouts/default" at line 1. in /home/example/craft/app/vendor/twig/twig/lib/Twig/Parser.php:178

is this anything to be concerned about?

**Comment by ghost** [comment]
In debugging further I found this:

Moving Craft's plugin folder outside of the craft folder caused the cacheflag add-on to not be found.

But this was only happening for locale's that were not en_us.

This may be not related to cacheflag.

**Comment by mmikkel** [comment]
Hey @mjatharvest, thanks for contributing – I concur that this doesn't really seem like an issue w/ Cache Flag. Hope you solved the problem, though!
